# Generated by Django 6.1 on 2026-09-13 02:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('rank', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('consulting', 'Consulting'), ('design', 'Design'), ('community', 'Community Outreach'), ('technical', 'Technical'), ('strategy', 'Strategy')], default='technical', max_length=20)),
                ('project_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
